# Generated by Django 5.1.1 on 2024-09-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(null=True, to='posts.image'),
        ),
    ]
