# Generated by Django 5.1.1 on 2024-09-19 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comment_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
    ]
