# Generated by Django 5.1.1 on 2024-09-22 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_comment_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='posts.comment')),
            ],
        ),
    ]
