# Generated by Django 5.1.1 on 2024-09-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_follower_options_follower_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bioo',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
