# Generated by Django 5.1.1 on 2024-09-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_user_bioo_user_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bioo',
            new_name='bio',
        ),
    ]
